apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: madina-app
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: us-west1-docker.pkg.dev/medina-474505/madina-repo/nginx:latest
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"

        - name: backend
          image: us-west1-docker.pkg.dev/medina-474505/madina-repo/backend:latest
          env:
            - name: APP_PORT
              value: "9000"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"

      containerConcurrency: 80
      timeoutSeconds: 600
